Repository kosmos-io/kosmos-website, pull requests merged in 2024-03, with the labels that each got.

#15 docs: add README.md file
  README.md
Labels: lgtm, approved, size/M

#18 fix: fix multi-cluster-network.md and pv-pvc-dynamic-storage.md
  kosmos/docs/v0.2.0/tutorials/multi-cluster-network.md
  kosmos/docs/v0.2.0/tutorials/pv-pvc-dynamic-storage.md
Labels: lgtm, approved, size/M

#19 docs: add application migration solution
  README.md
  docs/404.html
  docs/assets/js/135c4066.1ba5bd35.js
  docs/assets/js/135c4066.238260bf.js
  docs/assets/js/4b29c545.c58f40a8.js
  docs/assets/js/551e372e.38a74c14.js
  docs/assets/js/551e372e.67757be6.js
  docs/assets/js/69fd573f.5cd93c1c.js
  docs/assets/js/69fd573f.81aa7a2a.js
  docs/assets/js/935f2afb.8519e7b5.js
  docs/assets/js/935f2afb.f6f30526.js
  docs/assets/js/b4ae384a.8ec3beec.js
  docs/assets/js/b4ae384a.a3cc8f3a.js
  docs/assets/js/main.184346e0.js
  docs/assets/js/main.184346e0.js.LICENSE.txt
  docs/assets/js/main.38c0fa2d.js
  docs/assets/js/runtime~main.a16ccbac.js
  docs/assets/js/runtime~main.dfecd1d2.js
  docs/example/describe2.html
  docs/example/list1/test1.html
  docs/example/list2/test2.html
  docs/example/list3/list3Content.html
  docs/example/list3/test3.html
  docs/index.html
  docs/markdown-page.html
  docs/sitemap.xml
  docs/v0.2.0/getting-started/introduction.html
  docs/v0.2.0/proposals/distribution-policy.html
  docs/v0.2.0/proposals/k8s-in-k8s.html
  docs/v0.2.0/proposals/leaf-node-generate-rules.html
  docs/v0.2.0/quick-start.html
  docs/v0.2.0/tutorials/application-migration.html
  docs/v0.2.0/tutorials/exe-and-log.html
  docs/v0.2.0/tutorials/ipsec-network.html
  docs/v0.2.0/tutorials/mc-scheduler.html
  docs/v0.2.0/tutorials/mcn-connectivity.html
  docs/v0.2.0/tutorials/mcs-discovery.html
  docs/v0.2.0/tutorials/node-not-ready.html
  docs/v0.2.0/tutorials/pv-pvc-dynamic-storage.html
  kosmos/docs/v0.2.0/tutorials/application-migration.md
  kosmos/sidebars.js
Labels: lgtm, approved, size/L

#21 fix some minor issues
  kosmos/docs/v0.2.0/getting-started/introduction.md
Labels: lgtm, approved, size/S

#20 docs: update quickstart.md and README.md
  README.md
  kosmos/docs/v0.2.0/quickstart.md
Labels: lgtm, approved, size/L

#22 fix: Optimize article description
  kosmos/docs/v0.2.0/tutorials/design-of-exec-and-log.md
  kosmos/docs/v0.2.0/tutorials/img/EXEC_Log_Arch.png
  kosmos/docs/v0.2.0/tutorials/img/EXE_Log_2.png
  kosmos/docs/v0.2.0/tutorials/img/EXE_Log_3.png
Labels: size/M

#23 fix: use kyverno to block pod evicted when 'kosmos node not ready'
  kosmos/docs/v0.2.0/tutorials/node-not-ready.md
Labels: lgtm, approved
